Development
sanelca/Micro-Reddit pull request #1
Opened 2019-01-30 09:41 UTC by osinakayah

2019-02-04 08:18 UTC, talihomz commented
Hi @osinakayah 

This runs ok, was able to create a user, as well as play with the associations for Posting and commenting, great work.

There are a few things we that need clarification in the code.

2019-02-15 11:30 UTC, sanelca commented
@talihomz 
"There are a few things we that need clarification in the code."
Why you did not write your comments about code here?

2019-03-15 11:39 UTC, osinakayah commented
@talihomz Please, what are the things you need clarifications for?

2019-03-15 11:46 UTC, talihomz requested changes

2019-03-15 11:46 UTC, talihomz commented on app/controllers/comments_controller.rb
> +    @comment.user_id = 1
Why is this `user_id` hard coded?

2019-03-15 11:46 UTC, talihomz commented on app/controllers/posts_controller.rb
> +    @user = User.find(1)
Why is this `user_id` hard-coded?

2019-03-15 11:46 UTC, talihomz commented on app/controllers/posts_controller.rb
> +    @comment.user_id = 1
Hard-coded `user_id`.

2019-03-15 11:48 UTC, talihomz commented
Hi @osinakayah @osinakayah. I'm terribly sorry for leaving you hanging on this!

On Github, when you click on "Start Review", apparently one also needs to finalize by clicking "Request Changes" for them to appear here, and I was only aware of this now! 🙏🏼
 
I've posted them here, and again I am terribly sorry about this!

2019-03-15 11:50 UTC, sanelca commented on app/controllers/comments_controller.rb
> +    @comment.user_id = 1
That is a really big issue...  Do you have any another comment like that? Thank you... We will resolve that.

2019-03-15 11:51 UTC, sanelca commented on app/controllers/posts_controller.rb
> +    @user = User.find(1)
We will replace that...

2019-03-15 11:51 UTC, sanelca commented on app/controllers/posts_controller.rb
> +    @comment.user_id = 1
Thank you.

2019-03-15 11:56 UTC, sanelca commented
> Hi @osinakayah @osinakayah. I'm terribly sorry for leaving you hanging on this!
> 
> On Github, when you click on "Start Review", apparently one also needs to finalize by clicking "Request Changes" for them to appear here, and I was only aware of this now! 🙏🏼
> 
> I've posted them here, and again I am terribly sorry about this!

It is Ok we will resolve issues and make new review request :)

2019-03-21 12:39 UTC, closed without merging